// <auto-generated />
using System;
using System.Text.Json;
using ExcelArchive.Infrastructure.Implementations.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExcelArchive.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExcelArchive.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<JsonDocument>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_name");

                    b.HasKey("Id")
                        .HasName("pk_activity_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_activity_log_created_at");

                    b.ToTable("activity_log", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.ConflictCacheState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_conflict_cache_state");

                    b.ToTable("conflict_cache_state", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.ConflictQueryCache", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateOnly>("CheckedDate")
                        .HasColumnType("date")
                        .HasColumnName("checked_date");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("RebuiltAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("rebuilt_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.HasKey("Key")
                        .HasName("pk_conflict_query_cache");

                    b.HasIndex("RebuiltAt")
                        .HasDatabaseName("ix_conflict_query_cache_rebuilt_at");

                    b.ToTable("conflict_query_cache", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.DataQualityIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColumnName")
                        .HasColumnType("text")
                        .HasColumnName("column_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("issue_type");

                    b.Property<string>("RawValue")
                        .HasColumnType("text")
                        .HasColumnName("raw_value");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index");

                    b.HasKey("Id")
                        .HasName("pk_data_quality_issues");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_data_quality_issues_file_id");

                    b.HasIndex("FileId", "IssueType")
                        .HasDatabaseName("ix_data_quality_issues_file_id_issue_type");

                    b.ToTable("data_quality_issues", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColumnSignature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("column_signature");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sheet_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_files_group_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_files_name");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.FileColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("integer")
                        .HasColumnName("column_index");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("HeaderNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("header_normalized");

                    b.Property<string>("HeaderRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("header_raw");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StandardField")
                        .HasColumnType("varchar")
                        .HasColumnName("standard_field");

                    b.HasKey("Id")
                        .HasName("pk_file_columns");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_file_columns_category_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_columns_file_id");

                    b.HasIndex("CategoryId", "SortOrder")
                        .HasDatabaseName("ix_file_columns_category_id_sort_order");

                    b.HasIndex("FileId", "ColumnIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_file_columns_file_id_column_index");

                    b.ToTable("file_columns", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_name");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.IgnoredConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule");

                    b.HasKey("Id")
                        .HasName("pk_ignored_conflicts");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("ix_ignored_conflicts_record_id");

                    b.HasIndex("Rule")
                        .HasDatabaseName("ix_ignored_conflicts_rule");

                    b.HasIndex("Rule", "RecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_ignored_conflicts_rule_record_id");

                    b.ToTable("ignored_conflicts", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.MappingTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("HeaderSignature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("header_signature");

                    b.Property<JsonDocument>("Mapping")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mapping");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_mapping_templates");

                    b.HasIndex("GroupId", "HeaderSignature")
                        .HasDatabaseName("ix_mapping_templates_group_id_header_signature");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mapping_templates_group_id_name");

                    b.ToTable("mapping_templates", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DNationalId")
                        .HasColumnType("text")
                        .HasColumnName("d_national_id");

                    b.Property<string>("DPersonalNo")
                        .HasColumnType("text")
                        .HasColumnName("d_personal_no");

                    b.Property<string>("DPhone")
                        .HasColumnType("text")
                        .HasColumnName("d_phone");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<JsonDocument>("FmtFills")
                        .HasColumnType("jsonb")
                        .HasColumnName("fmt_fills");

                    b.Property<JsonDocument>("FmtFontColors")
                        .HasColumnType("jsonb")
                        .HasColumnName("fmt_font_colors");

                    b.Property<string>("NContractCode")
                        .HasColumnType("text")
                        .HasColumnName("n_contract_code");

                    b.Property<string>("NFatherName")
                        .HasColumnType("text")
                        .HasColumnName("n_father_name");

                    b.Property<string>("NFirstName")
                        .HasColumnType("text")
                        .HasColumnName("n_first_name");

                    b.Property<string>("NFullName")
                        .HasColumnType("text")
                        .HasColumnName("n_full_name");

                    b.Property<string>("NJobTitle")
                        .HasColumnType("text")
                        .HasColumnName("n_job_title");

                    b.Property<string>("NLastName")
                        .HasColumnType("text")
                        .HasColumnName("n_last_name");

                    b.Property<string>("NMotherName")
                        .HasColumnType("text")
                        .HasColumnName("n_mother_name");

                    b.Property<string>("NOrganizationalLevel")
                        .HasColumnType("text")
                        .HasColumnName("n_organizational_level");

                    b.Property<string>("NSecondaryContractCode")
                        .HasColumnType("text")
                        .HasColumnName("n_secondary_contract_code");

                    b.Property<long?>("NationalIdNum")
                        .HasColumnType("bigint")
                        .HasColumnName("national_id_num");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index");

                    b.Property<string>("SfContractCode")
                        .HasColumnType("text")
                        .HasColumnName("sf_contract_code");

                    b.Property<string>("SfFatherName")
                        .HasColumnType("text")
                        .HasColumnName("sf_father_name");

                    b.Property<string>("SfFirstName")
                        .HasColumnType("text")
                        .HasColumnName("sf_first_name");

                    b.Property<string>("SfFullName")
                        .HasColumnType("text")
                        .HasColumnName("sf_full_name");

                    b.Property<int?>("SfFunctionalCategory")
                        .HasColumnType("integer")
                        .HasColumnName("sf_functional_category");

                    b.Property<string>("SfJobTitle")
                        .HasColumnType("text")
                        .HasColumnName("sf_job_title");

                    b.Property<string>("SfLastName")
                        .HasColumnType("text")
                        .HasColumnName("sf_last_name");

                    b.Property<string>("SfMotherName")
                        .HasColumnType("text")
                        .HasColumnName("sf_mother_name");

                    b.Property<long?>("SfNationalId")
                        .HasColumnType("bigint")
                        .HasColumnName("sf_national_id");

                    b.Property<string>("SfOrganizationalLevel")
                        .HasColumnType("text")
                        .HasColumnName("sf_organizational_level");

                    b.Property<string>("SfPersonalNo")
                        .HasColumnType("text")
                        .HasColumnName("sf_personal_no");

                    b.Property<string>("SfPhone")
                        .HasColumnType("text")
                        .HasColumnName("sf_phone");

                    b.Property<string>("SfSecondaryContractCode")
                        .HasColumnType("text")
                        .HasColumnName("sf_secondary_contract_code");

                    b.Property<long?>("SfShamCash")
                        .HasColumnType("bigint")
                        .HasColumnName("sf_sham_cash");

                    b.HasKey("Id")
                        .HasName("pk_records");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_records_file_id");

                    b.HasIndex("NationalIdNum")
                        .HasDatabaseName("ix_records_national_id_num");

                    b.HasIndex("FileId", "RowIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_records_file_id_row_index");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.RecordEdit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("FileColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_column_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("HeaderRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("header_raw");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.HasKey("Id")
                        .HasName("pk_record_edits");

                    b.HasIndex("FileColumnId")
                        .HasDatabaseName("ix_record_edits_file_column_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_record_edits_file_id");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("ix_record_edits_record_id");

                    b.HasIndex("FileId", "CreatedAt")
                        .HasDatabaseName("ix_record_edits_file_id_created_at");

                    b.ToTable("record_edits", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.UploadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("finished_at");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("status");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.HasKey("Id")
                        .HasName("pk_upload_jobs");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_upload_jobs_file_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_upload_jobs_status");

                    b.ToTable("upload_jobs", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permissions");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_user_permissions_file_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_user_permissions_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_permissions_user_id");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.DataQualityIssue", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.File", "File")
                        .WithMany("DataQualityIssues")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_quality_issues_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.File", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.Group", "Group")
                        .WithMany("Files")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_files_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.FileColumn", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.Category", "Category")
                        .WithMany("Columns")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_file_columns_categories_category_id");

                    b.HasOne("ExcelArchive.Domain.Entities.File", "File")
                        .WithMany("Columns")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_columns_files_file_id");

                    b.Navigation("Category");

                    b.Navigation("File");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.IgnoredConflict", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.Record", "Record")
                        .WithMany("Ignores")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ignored_conflicts_records_record_id");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.MappingTemplate", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.Group", "Group")
                        .WithMany("Templates")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mapping_templates_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.Record", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.File", "File")
                        .WithMany("Records")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_records_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.RecordEdit", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.FileColumn", "FileColumn")
                        .WithMany("RecordEdits")
                        .HasForeignKey("FileColumnId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_record_edits_file_columns_file_column_id");

                    b.HasOne("ExcelArchive.Domain.Entities.File", "File")
                        .WithMany("RecordEdits")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_record_edits_files_file_id");

                    b.HasOne("ExcelArchive.Domain.Entities.Record", "Record")
                        .WithMany("Edits")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_record_edits_records_record_id");

                    b.Navigation("File");

                    b.Navigation("FileColumn");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.UploadJob", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.File", "File")
                        .WithMany("UploadJobs")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_upload_jobs_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("ExcelArchive.Domain.Entities.File", "File")
                        .WithMany("ScopedPermissions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_permissions_files_file_id");

                    b.HasOne("ExcelArchive.Domain.Entities.Group", "Group")
                        .WithMany("ScopedPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_permissions_groups_group_id");

                    b.HasOne("ExcelArchive.Domain.Entities.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");

                    b.Navigation("File");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.Category", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.File", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("DataQualityIssues");

                    b.Navigation("RecordEdits");

                    b.Navigation("Records");

                    b.Navigation("ScopedPermissions");

                    b.Navigation("UploadJobs");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.FileColumn", b =>
                {
                    b.Navigation("RecordEdits");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.Group", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("ScopedPermissions");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.Record", b =>
                {
                    b.Navigation("Edits");

                    b.Navigation("Ignores");
                });

            modelBuilder.Entity("ExcelArchive.Domain.Entities.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
