namespace ExcelArchive.Domain.Entities;

public class RecordEdit
{
    public Guid Id { get; set; } = Guid.NewGuid();
    /// <summary>Owning record. Null for edits archived from a previous file
    /// version: the old rows are replaced on update, but the edit log itself
    /// is preserved and stays visible in the edit history (never on the
    /// record page, which only shows current-version edits).</summary>
    public Guid? RecordId { get; set; }
    public Guid FileId { get; set; }
    public Guid? FileColumnId { get; set; }
    /// <summary>File version this edit was made on. Archived edits keep the
    /// old version number so history can label them (V1, V2, ...).</summary>
    public int FileVersion { get; set; } = 1;
    public string HeaderRaw { get; set; } = "";
    public string OldValue { get; set; } = "";
    public string NewValue { get; set; } = "";
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Username of whoever made this edit (V2 addition; null for
    /// legacy rows recorded before the field existed).</summary>
    public string? EditedBy { get; set; }

    /// <summary>True for bulk-audit rows auto-generated by a file update
    /// (the update's own content), as opposed to manual human edits. Bulk
    /// rows never count as "pending" edits and never flag preview cells as
    /// manually edited.</summary>
    public bool IsBulk { get; set; }

    /// <summary>Normalized (11-char, zero-padded) national ID of the edited
    /// person at edit time. Stable row identity: unlike Excel row numbers it
    /// survives row deletions/insertions and file replacements, so archived
    /// edits (null record id) can still resolve the CURRENT record and its
    /// current value. Null when the file has no (valid) national-id column.</summary>
    public string? NationalId { get; set; }

    public Record? Record { get; set; }
    public File File { get; set; } = null!;
    public FileColumn? FileColumn { get; set; }
}
